### ISSUE TITLE
General Issues with all Commands

### ISSUE THREAD

**Issue by JeffreyShewell** [impiprogrammers/frc-1025-robot-2020#11]
All commands should have private final variables for all the subsystems it uses.  The constructor should take all those subsystems as a variable at set the member.

There should be commands to extend, retract, and toggle all pneumatic components even if we may not use them.  For example, you only have a toggle command for the intake.  We need commands in auto to extend and retract it for autonomous.  This can be done by sub-classing the InstantCommand.  Mitch, this is not wrong.  See ReleaseHatch in the Hatchbot example.  That's exactly what I did.

For all subsystems with motors, there should be commands to run at a general speed (usually for autonomous). For example, you only have a command to drive the conveyor with a joystick.  There is no way to drive it during autonomous.

All commands that use joysticks (default commands for the subsystems) should have a command that takes the joystick axis as a DoubleSupplier.  The joysticks should not be accessed directly in the command.

**Comment by impiprogrammers** [comment]
I believe this is all done; if I missed anything let me know.
-Gwynn
