### ISSUE TITLE
Issues with Turret Subsystem

### ISSUE THREAD

**Issue by JeffreyShewell** [impiprogrammers/frc-1025-robot-2020#12]
There shouldn't be a crapload of functions to change the color that are all nearly identical.  There should be one function that takes the color as an argument.
There should be no public variables!  Set everything as private.
It would be a lot cleaner to move the LED's to its own subsystem then have the default command for the LED subsystem update the colors/blnking.
The turret soft stops should be constants in the Constants file.

**Comment by Miles-K** [comment]
There shouldn't be a crap_load of functions to change the color that are all nearly identical. There should be one function that takes the color as an argument. [not done]
There should be no public variables! Set everything as private. [done w/ turret]
It would be a lot cleaner to move the LED's to its own subsystem then have the default command for the LED subsystem update the colors/blinking. [done]
The turret soft stops should be constants in the Constants file. [done]
