### ISSUE TITLE
Issues with ChassisSubsystem

### ISSUE THREAD

**Issue by JeffreyShewell** [impiprogrammers/frc-1025-robot-2020#6]
Need to set the velocity conversion factor.

**Comment by impiprogrammers** [comment]
Hi, Gwynn here.

I set the velocity conversion factor to the same factor as for position. I'm not sure if this is correct; the REVRobotics documentation doesn't say anything on the matter. Let me know if this is wrong.

**Comment by JeffreyShewell** [comment]
The velocity conversion factor should be the position conversion factor / 60.
